# Do not change anything in here unless you know what you're doing!

name: ShopChest
main: de.epiceric.shopchest.ShopChest
version: 1.8.0-SNAPSHOT-1
author: EpicEric
website: https://www.spigotmc.org/resources/shopchest.11431/
depend: [Vault]
softdepend: [ClearLag, LWC, Lockette]
loadbefore: [ItemTags]

permissions:
  shopchest.*:
    description: Gives access to all ShopChest permissions.
    children:
      shopchest.create: true
      shopchest.removeOther: true
      shopchest.buy: true
      shopchest.openOther: true
      shopchest.notification.update: true
      shopchest.reload: true
      shopchest.update: true
      shopchest.limits: true
  shopchest.create:
    description: Allows you to create a shop.
    default: true
  shopchest.create.admin:
    description: Allows you to create an admin shop.
    children:
      shopchest.create: true
    default: op
  shopchest.create.protected:
    description: Allows you to create a shop on a protected chest.
    children:
      shopchest.create: true
    default: op
  shopchest.removeOther:
    description: Allows you to remove other players' shop.
    default: op
  shopchest.buy:
    description: Allows you to buy something.
    default: true
  shopchest.sell:
    description: Allows you to sell something.
    default: true
  shopchest.openOther:
    description: Allows you to open other players' shop.
    default: op
  shopchest.notification.update:
    description: Allows you to get update notification on join.
    default: op
  shopchest.reload:
    description: Allows you to reload the shops.
    default: op
  shopchest.update:
    description: Allows you to check for updates.
    default: op
  shopchest.limits:
    description: Allows you to view shop limits.
    default: true
  shopchest.broadcast:
    description: Allows you to get broadcast messages.
    default: op